version: '2.1'

services:
  postgres-db:
    container_name: postgres-db
    build: ./project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  flask-service:
    container_name: flask-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@postgres-db:5432/flask_service_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@postgres-db:5432/flask_service_test
    depends_on:
      postgres-db:
        condition: service_healthy
    links:
      - postgres-db